# fly.toml app configuration file generated for numble on 2023-08-29T18:55:33-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "numble"
primary_region = "ord"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE="django-app.prod_settings"


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
